### ISSUE TITLE
Issue tracker parses templater tp.system.suggester twice

### ISSUE THREAD

**Issue by doug-w** [ljavuras/obsidian-power-tools#6]
I have the following in the frontmatter section of an issue-tracker.issue template:
---
type: <% tp.system.suggester(["Story", "Bug", "TODO", "Epic"], ["Story", "Bug", "TODO", "Epic"], false, "Type of Issue") %>
issueNo: <% issueInfo.issueNo %>
labels:<% issueInfo.labelsYAML %>
---

When I open a new issue the Type of Issue pops up, and then pops up a second time, the value of the second time is the one that is actually used in the new document.

**Comment by ljavuras** [comment]
I can't reproduce the behavior you described, are you still experiencing the same issue?

**Comment by doug-w** [comment]
No it's fixed now either with more recent obsidian or templater.  Thanks for trying to repro though I appreciate your work!
