### ISSUE TITLE
Periodic Notes Navigation do not trigger Periodic Notes templates

### ISSUE THREAD

**Issue by zigotica** [ljavuras/obsidian-power-tools#7]
How can I modify the templates from template-simple folder so that they insert a new periodic note using the predefined templates?

Note: `Trigger Templater on new file creation` and `Periodic Note` settings are properly working when used from the command menu. 

Thank you

**Comment by ljavuras** [comment]
Use [filename template](https://github.com/ljavuras/obsidian-power-tools/tree/main/Filename%20Template).

Periodic Note doesn't detect new file creation and insert appropriate templates. The workaround is to use Templater's `Folder Templates` feature to insert a special template, whose single purpose is to insert another template based on file name.

When you click on a link that follows a format, for example "YYYY-MM-DD", this special filename template will insert your daily template for you.
